### ISSUE TITLE
Add slicing ability to poses

### ISSUE THREAD

**Issue by AmitMY** [sign-language-processing/pose#32]
I find myself doing the following in many projects:
```py
pose.body.data = pose.body.data[start:end]
pose.body.confidence = pose.body.confidence[start:end]
```

a better API for this would be both on `Pose` and `PoseBody`:
```py
pose = pose[start:end]
```
and
```py
pose.body = pose.body[start:end]
```

**Comment by gegallego** [comment]
Hi Amit!

We have a suggestion similar to what you propose here. We think it could be great to have the possibility to load `.pose` files specifying a `start`and `end`.

In the preprocessing we did for the WMT-SLT, we decided to extract poses for the entire videos, and then build a TSV where every row is like `<pose_file>\t<start_frame>\t<end_frame>\t<translation>`. The problem is that it is REALLY inefficient (specially if the original videos are long) because we have to load the whole `.pose` file and then slice it.

Do you think it would be easy to implement?

**Comment by bricksdont** [comment]
Hi @gegallego Could you give a code example of the feature you have in mind? Thanks!

**Comment by gegallego** [comment]
Sure, the idea is loading pose files with something like:
```
with open(feats_file, "rb") as f:
    pose = Pose.read(f.read(), start, end)
```

Where, internally, it skips loading anything outside the range [`start`, `end`].
